index.html

feature: semantic HTML boilerplate code

---

index.html
styles.css

+ background colours
+ link in html to google fonts
+ body font
+ section height

+css background styling +html font link 

---

index.html
styles.css

Relates #15
Added parent div to opening section button for styling.
Added font styling and padding to opening section text.
Hid H3 opening section tagline.

Add font styling to opening section

---

index.html
styles.css

Center elements vertically in opener section and filler1

---

index.html

more content to style, let's GO!

Introduction html content

---

index.html

feat: add filler2 HTML content

---

index.html

feat: add "meet the team" HTML content

---

index.html

fix: add final introduction image

---

index.html

feat: add contact form HTML

---

index.html
styles.css

Add grid layout to introduction, add font styling

---

index.html
styles.css

Relates #45 
Relates #46  
Relates #40

Form submission and styling

---

index.html
scripts.js
styles.css

feat: add navbar functionality

---

styles.css

Replaced duplicate CSS values with variables.

---

index.html
styles.css

Form button fix

---

index.html
styles.css

feat: add navbar icons

---

styles.css

fix: tweak navbar font sizes

---

styles.css

fix: add button hover/active styles

---

index.html
styles.css

feat: add footer content

---

index.html

fix: remove unused favicon link

---

index.html

fix: edit form labels
